# ===== Application =====
spring.application.name=student-management
server.port=8080

# ===== DataSource: SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH6;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Map m?i String -> NVARCHAR ?? l?u ???c ti?ng Vi?t
spring.jpa.properties.hibernate.use_nationalized_character_data=true
# T?t Open Session In View: m?i truy c?p DB ph?i xong trong Service
spring.jpa.open-in-view=false

# ===== Thymeleaf =====
spring.thymeleaf.cache=false

# ===== Logging =====
logging.level.com.hsf302=DEBUG