spring.main.banner-mode=off

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HSF302_CH4;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
